name: Lint
on:
  push:
    branches:
      - master
  pull_request:
env:
  FORCE_COLOR: 2
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          install-command: yarn --silent
      - name: Run linters
        run: yarn lint
